/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github.com.yadavsudhir405;

import org.apache.commons.lang3.StringUtils;

public class App {
    public String getGreeting() {

        return StringUtils.upperCase("Hello world.");
    }

    public String toUpperCase(String str){
        return StringUtils.upperCase(str);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
