/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github.com.yadavsudhir405;

import github.com.yadavsudhir405.forkjoin.ForkJoinRunner;


public class App {
    public static void main(String[] args) throws Exception {
    }
}
